services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: sync
      POSTGRES_PASSWORD: sync
      POSTGRES_DB: sync
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql
volumes:
  postgres:
